//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcEmpleados
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIAJES
    {
        public int ID_VIAJE { get; set; }
        public string ORIGEN { get; set; }
        public string DESTINO { get; set; }
        public System.TimeSpan T_TRANSCURRIDO_H { get; set; }
        public string NOM_PASAJERO { get; set; }
        public int ID_VEHICULO { get; set; }
        public int ID_EMP { get; set; }
        public System.DateTime HORA_VIAJE { get; set; }
    
        public virtual EMPLEADOS EMPLEADOS { get; set; }
        public virtual VEHICULOS VEHICULOS { get; set; }
    }
}
